### PR TITLE
fix(leak): don't mutate logger, just make events from it

### LINKED ISSUE #68: #65 per-request allocation reduction destroys this module
PR #65, in an attempt to reduce allocations, actually wrecks this module and makes the output insane in some cases, and introduces a humongous memory leak.

The problem is that the returned `gin.HandlerFunc` closes over `l` the logger variable. Therefore, requests stomp over each other, modifying the same context buffers inside the logger, as a nice data race for good measure, and overall resulting in the data from every request ever issued being captured, leaking memory and making a mess of the output.

https://github.com/gin-contrib/logger/blob/7cff53ef985497b0fa890e08235fffdcc1e900d0/logger.go#L107-L113

The tests didn't notice this because they all use a `ConsoleWriter`, which obscures this duplication.

I think the fix is simple: create an _event_ at that line instead of mutating the logger. Submitted #69 with a fix for this, and a test which demonstrates the issue.

### PR DESCRIPTION
**Pull request by mgabeler-lee-6rs**
fixes: #68, #78

The bug also appears without using the customized logger, but it only manifests as a memory leak because the `ConsoleWriter` obscures the duplicate data in the logger context.

When using a custom logger, reproducing the issue requires concurrent requests ... which is a pretty common thing in real apps :)

### CODE REVIEW

**Comment by oliver202301** [comment]
Hi
When do you expect to merge this pull request?

**Comment by mgabeler-lee-6rs** [comment]
I have no control over that, it requires a maintainer to review & merge it

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@mgabeler-lee-6rs Could you help to fix the conflicts?

**Comment by mgabeler-lee-6rs** [comment]
@appleboy done!

**Comment by oltur** [comment]
Please merge, it is really annoying

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
See the release https://github.com/gin-contrib/logger/releases/tag/v1.1.0

**Pull request merged**
